import { StyleSheet } from 'react-native';

const RED = '#c21c1c';
const BG  = '#f7f7f9';

export const styles = StyleSheet.create({
    // ── Scroll / contenedor ──────────────────────────────
    scrollContent: {
        backgroundColor: BG,
        paddingBottom: 40,
    },

    // ── Header rojo ──────────────────────────────────────
    headerBlock: {
        backgroundColor: RED,
        paddingTop: 20,
        paddingBottom: 28,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 28,
        borderBottomRightRadius: 28,
        marginBottom: 16,
        elevation: 8,
        shadowColor: RED,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
    },
    headerTitulo: {
        fontSize: 26,
        fontWeight: '800',
        color: '#fff',
        marginBottom: 6,
    },
    estadoBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 14,
        paddingVertical: 5,
        borderRadius: 20,
        overflow: 'hidden',
    },
    estadoTexto: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 12,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },

    // ── Sección items ─────────────────────────────────────
    seccionLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#aaa',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginHorizontal: 16,
        marginBottom: 8,
    },
    item: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 14,
        marginHorizontal: 16,
        marginBottom: 10,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
    },
    itemNombre: {
        fontSize: 16,
        fontWeight: '800',
        color: '#111',
        marginBottom: 4,
    },
    itemDetalle: {
        fontSize: 13,
        color: '#777',
        marginBottom: 2,
    },
    itemTotal: {
        fontSize: 14,
        fontWeight: '700',
        color: '#333',
        marginBottom: 8,
    },
    // Controles +/- 
    itemControles: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 4,
    },
    controlBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
    },
    controlBtnRed: {
        backgroundColor: '#fff0f0',
    },
    controlBtnText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#333',
        lineHeight: 20,
    },
    cantidadText: {
        fontSize: 16,
        fontWeight: '800',
        color: '#111',
        minWidth: 24,
        textAlign: 'center',
    },

    // ── Resumen financiero ────────────────────────────────
    resumenCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        marginHorizontal: 16,
        marginTop: 4,
        marginBottom: 16,
        padding: 18,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    resumenFila: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
    },
    resumenDivider: {
        height: 1,
        backgroundColor: '#f0f0f0',
        marginVertical: 8,
    },
    resumenLabel: {
        fontSize: 14,
        color: '#777',
        fontWeight: '500',
    },
    resumenValorTotal: {
        fontSize: 18,
        fontWeight: '800',
        color: '#111',
    },
    resumenValorPagado: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1e8c3a',
    },
    resumenValorPendiente: {
        fontSize: 15,
        fontWeight: '700',
        color: RED,
    },
    resumenValorCambio: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1e8c3a',
    },

    // ── Barra de acciones ─────────────────────────────────
    actionsBar: {
        paddingHorizontal: 16,
        paddingBottom: 20,
        paddingTop: 8,
        gap: 10,
    },
    botonCompletar: {
        backgroundColor: '#111',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
    },
    botonFila: {
        flexDirection: 'row',
        gap: 10,
    },
    botonAbonar: {
        flex: 1,
        backgroundColor: '#6c2aa8',
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: 'center',
        elevation: 3,
        shadowColor: '#6c2aa8',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    botonAgregar: {
        flex: 1,
        backgroundColor: '#1565C0',
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: 'center',
        elevation: 3,
        shadowColor: '#1565C0',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    botonGuardar: {
        backgroundColor: RED,
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        elevation: 4,
        shadowColor: RED,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.35,
        shadowRadius: 6,
    },
    botonTexto: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 15,
        letterSpacing: 0.3,
    },

    // ── Modales ───────────────────────────────────────────
    modalFondo: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.45)',
        paddingHorizontal: 24,
    },
    modal: {
        backgroundColor: '#fff',
        borderRadius: 24,
        padding: 24,
        width: '100%',
        elevation: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.18,
        shadowRadius: 14,
    },
    modalTitulo: {
        fontSize: 20,
        fontWeight: '800',
        color: '#111',
        marginBottom: 16,
    },
    input: {
        backgroundColor: '#f5f5f5',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 12,
        fontSize: 16,
        color: '#111',
        borderWidth: 1.5,
        borderColor: '#eee',
    },
    pickerContainer: {
        backgroundColor: '#f5f5f5',
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1.5,
        borderColor: '#eee',
        overflow: 'hidden',
    },
    modalBotones: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        marginTop: 8,
    },
    cancelar: {
        color: '#888',
        fontWeight: '700',
        fontSize: 15,
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    aceptar: {
        backgroundColor: RED,
        color: '#fff',
        paddingVertical: 10,
        paddingHorizontal: 22,
        borderRadius: 12,
        fontWeight: '700',
        fontSize: 15,
        overflow: 'hidden',
    },

    // ── Loading ───────────────────────────────────────────
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: BG,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 14,
        color: '#888',
    },
});